name: Execute tests in docker-compose

on:
  push:
    branches: [ "dev", "4-add-ci-support-for-testing-and-building-docker-image" ]
  pull_request:
    branches: [ "dev", "4-add-ci-support-for-testing-and-building-docker-image" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Build software
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.test.yml pull  # Force download of any newer dependency images
        docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build
        docker-compose -f docker-compose.yml -f docker-compose.test.yml images  # Useful for debugging
        docker-compose -f docker-compose.yml -f docker-compose.test.yml images -q | xargs docker inspect | grep -C3 RepoTags  # Useful for debugging
      env:
        MAVEN_USER: ${{ github.actor }}
        # this secret needs to be able to do package:read in the organisation scope (the permissions set within this file are scoped to just this repo)
        MAVEN_PASS: ${{ secrets.PACKAGE_READ_SECRET }}

    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.test.yml ps -a
        docker ps
        docker-compose -f docker-compose.yml -f docker-compose.test.yml exec -T ssm sh -c "cd /system-modeller && ./gradlew test -PmavenUser=${{ github.actor }} -PmavenPass=${{ secrets.PACKAGE_READ_SECRET }}"
