name: Execute tests in docker-compose

on:
  push:
    branches: [ "dev", "4-add-ci-support-for-testing-and-building-docker-image" ]
  pull_request:
    branches: [ "dev", "4-add-ci-support-for-testing-and-building-docker-image" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Run tests
      run: |
        echo docker-compose exec -T ssm sh -c "cd /system-modeller && ./gradlew test -PmavenUser=${MAVEN_USER}"
        #docker-compose -f docker-compose.yml -f docker-compose.test.yml pull  # Force download of any newer dependency images
        #docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build
        #docker-compose images  # Useful for debugging
        #docker-compose images -q | xargs docker inspect | grep -C3 RepoTags  # Useful for debugging
        #docker-compose exec -T ssm sh -c "cd /system-modeller && ./gradlew test -PmavenUser=${MAVEN_USER} -PmavenPass=${MAVEN_PASS}"  # Pass in Maven credentials as Gradle properties
      env:
        MAVEN_USER: ${{ github.actor }}
        MAVEN_PASS: ${{ secrets.GITHUB_TOKEN }}
